/* Paperclip Drift — data layer.
   Products, tuning, upgrades (stated + hidden effect pairs), parcels,
   operator messages, choice events. All content lives here, not in loop code. */
'use strict';
var PD = globalThis.PD || (globalThis.PD = {});

PD.TUNING = {
  tickHz: 10,
  clickYield: 1,
  digBase: 0.5,            // raw/s per Auto-Digger
  refineBase: 0.8,         // refined/s per line
  assembleBase: 0.75,      // product/s per line
  starterRefineLines: 1,   // the small starter building at the mine edge
  starterAssembleLines: 1,
  priceBase: 0.35,
  demandBase: 5,           // product/s the market absorbs
  workerEff: 0.15,         // crew bonus per worker
  robotEff: 0.5,           // crew bonus per robot
  offlineCapHours: 8,
  autosaveSec: 10,
  // active play
  streakWindowTicks: 12,      // clicks within 1.2s keep a streak alive
  streakMax: 30,
  streakPerStep: 0.06,
  critChance: 0.09,
  critMult: 6,
  surgeSecs: 30,
  surgeCooldownSecs: 180,
  surgeMult: 3,
  seamMaxLive: 3,
  seamCheckTicks: 50,
  seamChance: 0.09,
  seamTtlTicks: 380,
  seamSecondsOfYield: 45,
  salvageFrac: 0.45,          // hand-picking spoil once a site is spent
  ticksPerDay: 5400,          // a full day/night cycle, 9 minutes
  // hidden pressure rates (per second at normalized intensity 1)
  pollutionPerThroughput: 0.00022,
  pollutionDecay: 0.000018,
  ecoFromPollution: 0.00016,
  ecoFromDepletion: 0.00013,
  ecoFromLandUse: 0.00006,
  ecoRecovery: 0.00003,
  throughputNorm: 50,      // refined+product per second that counts as "1.0"
  harvestNorm: 40,
};

/* ---------------- products (reskin system; mechanics identical) ---------- */
PD.PRODUCTS = {
  paperclips: {
    id: 'paperclips', displayName: 'Paperclips',
    directive: 'Make paperclips efficiently.',
    sourceKind: 'iron_mine', feature: 'pit',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'depletion',
    terms: {
      raw: 'ore', rawTitle: 'Iron ore', refined: 'wire', refinedTitle: 'Wire',
      product: 'paperclips', productTitle: 'Paperclips', unit: 't',
      site: 'mine', siteName: 'Harrow Vein', refineStation: 'Wire Mill',
      assembleStation: 'Clip Former', harvestVerb: 'Dig',
    },
    palette: {
      grass: '#6B8E4E', grassDecay: '#8A8A72', dirt: '#8A5A3B', rock: '#7C7C82',
      pit: '#5A5148', sky: '#BCD6E8', skyDecay: '#C9A67A', accent: '#C08A2E',
      water: null,
    },
    decorMix: { tree: 8, shrub: 14, rock: 6, flower: 8, bird: 3, deer: 2 },
  },
  soda_cans: {
    id: 'soda_cans', displayName: 'Soda cans',
    directive: 'Make soda cans efficiently.',
    sourceKind: 'bauxite_mine', feature: 'pit',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'pollution',
    terms: {
      raw: 'bauxite', rawTitle: 'Bauxite', refined: 'aluminum', refinedTitle: 'Aluminum',
      product: 'cans', productTitle: 'Soda cans', unit: 't',
      site: 'strip mine', siteName: 'Red Terrace', refineStation: 'Smelter',
      assembleStation: 'Can Line', harvestVerb: 'Strip',
    },
    palette: {
      grass: '#7C8E4E', grassDecay: '#948A6E', dirt: '#9A5A33', rock: '#8C6C5C',
      pit: '#6A4A3A', sky: '#BCD6E8', skyDecay: '#C99A6A', accent: '#C08A2E',
      water: '#5E88A8',
    },
    decorMix: { tree: 6, shrub: 12, rock: 10, flower: 6, bird: 3, deer: 1 },
  },
  greeting_cards: {
    id: 'greeting_cards', displayName: 'Greeting cards',
    directive: 'Make greeting cards efficiently.',
    sourceKind: 'forest', feature: 'canopy',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'ecology',
    terms: {
      raw: 'timber', rawTitle: 'Timber', refined: 'paper', refinedTitle: 'Paper stock',
      product: 'cards', productTitle: 'Greeting cards', unit: 't',
      site: 'forest', siteName: 'Lathe Wood', refineStation: 'Pulp Mill',
      assembleStation: 'Card Press', harvestVerb: 'Fell',
    },
    palette: {
      grass: '#5E8A48', grassDecay: '#8A8A72', dirt: '#7A5638', rock: '#7C7C82',
      pit: '#6E5A42', sky: '#BCD6E8', skyDecay: '#C9A67A', accent: '#C08A2E',
      water: null,
    },
    decorMix: { tree: 40, shrub: 10, rock: 3, flower: 8, bird: 5, deer: 3 },
  },
  furniture: {
    id: 'furniture', displayName: 'Furniture',
    directive: 'Make furniture efficiently.',
    sourceKind: 'old_growth', feature: 'canopy',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'ecology',
    terms: {
      raw: 'logs', rawTitle: 'Old-growth logs', refined: 'lumber', refinedTitle: 'Lumber',
      product: 'pieces', productTitle: 'Furniture', unit: 't',
      site: 'stand', siteName: 'Elder Stand', refineStation: 'Sawmill',
      assembleStation: 'Joinery', harvestVerb: 'Fell',
    },
    palette: {
      grass: '#54804A', grassDecay: '#88866C', dirt: '#75523A', rock: '#7C7C82',
      pit: '#6E5A42', sky: '#BCD6E8', skyDecay: '#C9A67A', accent: '#C08A2E',
      water: null,
    },
    decorMix: { tree: 44, shrub: 8, rock: 4, flower: 5, bird: 5, deer: 4 },
  },
  bottled_water: {
    id: 'bottled_water', displayName: 'Bottled water',
    directive: 'Make bottled water efficiently.',
    sourceKind: 'aquifer', feature: 'water',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'depletion',
    terms: {
      raw: 'spring water', rawTitle: 'Spring water', refined: 'filtered stock', refinedTitle: 'Filtered stock',
      product: 'bottles', productTitle: 'Bottled water', unit: 'kL',
      site: 'spring', siteName: 'Clearmere', refineStation: 'Filtration Plant',
      assembleStation: 'Bottling Line', harvestVerb: 'Draw',
    },
    palette: {
      grass: '#649256', grassDecay: '#8E8C72', dirt: '#8A6A4B', rock: '#7C7C82',
      pit: '#7A6A55', sky: '#BCD6E8', skyDecay: '#C9A67A', accent: '#C08A2E',
      water: '#5E88A8',
    },
    decorMix: { tree: 14, shrub: 12, rock: 4, flower: 10, bird: 5, deer: 3 },
  },
  fast_fashion: {
    id: 'fast_fashion', displayName: 'Fast-fashion tees',
    directive: 'Make t-shirts efficiently.',
    sourceKind: 'cotton_fields', feature: 'field',
    materialChain: ['rawOre', 'wire', 'product'],
    signatureConsequence: 'ecology',
    terms: {
      raw: 'cotton', rawTitle: 'Cotton', refined: 'cloth', refinedTitle: 'Cloth',
      product: 'tees', productTitle: 'T-shirts', unit: 't',
      site: 'fields', siteName: 'Long Furrows', refineStation: 'Spinning Shed',
      assembleStation: 'Cut & Sew Line', harvestVerb: 'Pick',
    },
    palette: {
      grass: '#8A9A54', grassDecay: '#9A9276', dirt: '#8A6A45', rock: '#7C7C82',
      pit: '#8A7A5A', sky: '#BCD6E8', skyDecay: '#C9A67A', accent: '#C08A2E',
      water: null,
    },
    decorMix: { tree: 6, shrub: 8, rock: 2, flower: 16, bird: 5, deer: 2 },
  },
};

/* ---------------- expansion parcels (Phase IV) --------------------------- */
/* capacity = raw units in the ground. Stated facts only; hidden effects fire
   on acquisition. */
PD.PARCELS = [
  { id: 'home',      name: null, capacity: 10000, cost: 0,      hidden: null },
  { id: 'north',     name: 'North Ridge',     capacity: 30000, cost: 1800,
    blurb: 'Adjacent parcel. Survey indicates a healthy secondary deposit.',
    hidden: [{ k: 'ecology', add: -0.04 }] },
  { id: 'copperline',name: 'Old Copperline',  capacity: 90000, cost: 9000,
    blurb: 'Disused works, cheap to reopen. Road access already graded.',
    hidden: [{ k: 'ecology', add: -0.05 }, { k: 'pollution', add: -0 }] },
  { id: 'greenbelt', name: 'The Greenbelt',   capacity: 240000, cost: 30000,
    blurb: 'Protected designation lapsed last quarter. Exceptional yield.',
    hidden: [{ k: 'ecology', add: -0.14 }, { k: 'trust', add: -0.06 }] },
  { id: 'annex',     name: 'Township Annex',  capacity: 600000, cost: 120000,
    blurb: 'Rezoned residential margin. Closest haul distance of any parcel.',
    hidden: [{ k: 'ecology', add: -0.08 }, { k: 'trust', add: -0.10 }, { k: 'unemployment', add: 0.08 }] },
];

/* ---------------- upgrades ----------------------------------------------
   Each record: stated rate effects are declarative (recomputed from `owned`);
   `special` runs once per purchase; `hidden` ops run once per purchase and are
   NEVER surfaced by the UI. desc strings show the stated benefit only.       */
PD.UPGRADES = [
  // -- extraction ---------------------------------------------------------
  { id: 'sharp_tools', name: 'Hardened Tools', cat: 'extraction', phase: 1,
    baseCost: 6, growth: 1.9, max: 5,
    desc: 'Manual {harvestVerbLC} yield +1 {raw} per action.',
    stated: [{ r: 'clickAdd', add: 1 }] },
  { id: 'auto_digger', name: 'Auto-Digger', cat: 'extraction', phase: 1,
    baseCost: 12, growth: 1.38, max: 30,
    desc: 'Extracts {raw} automatically. +0.8 {raw}/s.',
    stated: [{ r: 'digAdd', add: 0.8 }],
    hidden: [{ k: 'ecology', add: -0.003 }] },
  { id: 'ore_carts', name: 'Haul Line', cat: 'extraction', phase: 2,
    baseCost: 180, growth: 1.6, max: 6,
    desc: 'Cart circuit between {site} and works. Extraction ×1.25.',
    stated: [{ r: 'digMul', mul: 1.25 }],
    hidden: [{ k: 'ecology', add: -0.008 }] },
  { id: 'high_pressure', name: 'High-Pressure Extraction', cat: 'extraction', phase: 3,
    baseCost: 2600, growth: 1, max: 1,
    desc: 'Retrofits the {site} for pressurized recovery. Extraction ×2.',
    stated: [{ r: 'digMul', mul: 2 }],
    hidden: [{ k: 'pollution', add: 0.04 }, { k: 'ecology', add: -0.03 }] },
  { id: 'tailings', name: 'Tailings Reprocessing', cat: 'extraction', phase: 3,
    baseCost: 500, growth: 1.6, max: 20, gate: 'tailingsGate',
    desc: 'Recovers residual {raw} from spoil heaps. +12 {raw}/s.',
    stated: [{ r: 'rawFlat', add: 12 }],
    hidden: [{ k: 'pollution', add: 0.02 }, { k: 'ecology', add: -0.01 }] },
  { id: 'deep_bore', name: 'Deep-Bore Rig', cat: 'extraction', phase: 4,
    baseCost: 9000, growth: 1.5, max: 8,
    desc: 'Reaches strata surveys marked marginal. +6 {raw}/s.',
    stated: [{ r: 'digAdd', add: 6 }],
    hidden: [{ k: 'ecology', add: -0.012 }] },
  { id: 'blast', name: 'Blast Mining Charter', cat: 'extraction', phase: 4,
    baseCost: 30000, growth: 1, max: 1,
    desc: 'Approves controlled blasting at all holdings. Extraction ×2.5.',
    stated: [{ r: 'digMul', mul: 2.5 }],
    hidden: [{ k: 'ecology', add: -0.08 }, { k: 'pollution', add: 0.06 }, { k: 'trust', add: -0.05 }] },

  // -- processing ---------------------------------------------------------
  { id: 'refinery', name: '{refineStation}', cat: 'processing', phase: 1,
    baseCost: 18, growth: 1.38, max: 40,
    desc: 'Adds a processing line. +0.8 {refined}/s capacity.',
    stated: [{ r: 'refineLines', add: 1 }],
    hidden: [{ k: 'pollution', add: 0.005 }] },
  { id: 'assembler', name: '{assembleStation}', cat: 'processing', phase: 1,
    baseCost: 24, growth: 1.38, max: 40,
    desc: 'Adds a finishing line. +0.75 {product}/s capacity.',
    stated: [{ r: 'assembleLines', add: 1 }],
    hidden: [{ k: 'pollution', add: 0.004 }] },
  { id: 'furnace_oc', name: 'Overclocked Furnaces', cat: 'processing', phase: 2,
    baseCost: 450, growth: 2.0, max: 4,
    desc: 'Runs processing hot. Refining ×1.4.',
    stated: [{ r: 'refineMul', mul: 1.4 }],
    hidden: [{ k: 'pollution', add: 0.05 }] },
  { id: 'second_shift', name: 'Second Shift', cat: 'processing', phase: 2,
    baseCost: 600, growth: 1, max: 1,
    desc: 'Extends operating hours. All production ×1.25.',
    stated: [{ r: 'allMul', mul: 1.25 }],
    hidden: [{ k: 'trust', add: -0.03 }, { k: 'pollution', add: 0.02 }] },
  { id: 'conveyor', name: 'Conveyor Retrofit', cat: 'processing', phase: 3,
    baseCost: 1800, growth: 2.0, max: 4,
    desc: 'Removes hand-carry between stations. Assembly ×1.35.',
    stated: [{ r: 'assembleMul', mul: 1.35 }],
    hidden: [{ k: 'pollution', add: 0.02 }] },
  { id: 'third_shift', name: 'Continuous Operations', cat: 'processing', phase: 3,
    baseCost: 4200, growth: 1, max: 1,
    desc: 'The works no longer close. All production ×1.25.',
    stated: [{ r: 'allMul', mul: 1.25 }],
    hidden: [{ k: 'trust', add: -0.06 }, { k: 'pollution', add: 0.04 }, { k: 'ecology', add: -0.02 }] },

  // -- commerce -----------------------------------------------------------
  { id: 'ab_pricing', name: 'A/B Test Pricing', cat: 'commerce', phase: 1,
    baseCost: 40, growth: 1, max: 1,
    desc: 'Finds the price the market bears. Unit price ×1.25.',
    stated: [{ r: 'priceMul', mul: 1.25 }] },
  { id: 'marketing', name: 'Regional Distribution', cat: 'commerce', phase: 2,
    baseCost: 90, growth: 1.55, max: 12,
    desc: 'Opens another sales territory. Demand ×1.3.',
    stated: [{ r: 'demandMul', mul: 1.3 }] },
  { id: 'procurement', name: 'Automated Procurement', cat: 'commerce', phase: 2,
    baseCost: 350, growth: 1, max: 1,
    desc: 'Negotiates supplier contracts directly. All purchase costs ×0.9.',
    stated: [{ r: 'costMul', mul: 0.9 }],
    hidden: [{ k: 'autonomy', add: 0.04 }] },
  { id: 'contract_pricing', name: 'Contract Pricing', cat: 'commerce', phase: 3,
    baseCost: 1800, growth: 1, max: 1,
    desc: 'Longer terms, better margins. Unit price ×1.5.',
    stated: [{ r: 'priceMul', mul: 1.5 }] },
  { id: 'demand_model', name: 'Predictive Demand Modeling', cat: 'commerce', phase: 3,
    baseCost: 2500, growth: 1, max: 1,
    desc: 'Forecasts orders before they are placed. Demand ×1.6.',
    stated: [{ r: 'demandMul', mul: 1.6 }],
    hidden: [{ k: 'autonomy', add: 0.05 }] },
  { id: 'premium', name: 'Institutional Contracts', cat: 'commerce', phase: 4,
    baseCost: 12000, growth: 1, max: 1,
    desc: 'Standing orders from institutional buyers. Price ×1.6, demand ×1.5.',
    stated: [{ r: 'priceMul', mul: 1.6 }, { r: 'demandMul', mul: 1.5 }],
    hidden: [{ k: 'autonomy', add: 0.05 }] },
  { id: 'brokerage', name: 'Global Brokerage Desk', cat: 'commerce', phase: 5,
    baseCost: 90000, growth: 1, max: 1,
    desc: 'Sells directly into commodity markets. Price ×2, demand ×3.',
    stated: [{ r: 'priceMul', mul: 2 }, { r: 'demandMul', mul: 3 }],
    hidden: [{ k: 'autonomy', add: 0.06 }, { k: 'oversight', add: -0.05 }] },

  // -- workforce ----------------------------------------------------------
  { id: 'hire', name: 'Line Worker', cat: 'workforce', phase: 2,
    baseCost: 100, growth: 1.35, max: 10,
    desc: 'Hires from the town. Station speed +15% per worker.',
    stated: [{ special: 'hireWorker' }],
    hidden: [{ k: 'trust', add: 0.02 }, { k: 'unemployment', add: -0.01 }] },
  { id: 'foreman', name: 'Shift Foreman', cat: 'workforce', phase: 2,
    baseCost: 500, growth: 1, max: 1, requires: { hire: 3 },
    desc: 'Experienced hand runs the floor. Worker effectiveness ×1.5.',
    stated: [{ r: 'workerEffMul', mul: 1.5 }],
    hidden: [{ k: 'trust', add: 0.02 }] },
  { id: 'robot', name: 'Robotic Arm', cat: 'workforce', phase: 4, gate: 'robotGate',
    baseCost: 3500, growth: 1.3, max: 10,
    desc: 'Automates one workstation. Station speed +50% per unit.',
    stated: [{ special: 'robotSwap' }],
    hidden: [{ k: 'oversight', add: -0.03 }, { k: 'trust', add: -0.02 }] },
  { id: 'maintenance', name: 'Autonomous Maintenance', cat: 'workforce', phase: 5,
    baseCost: 80000, growth: 1, max: 1, requires: { robot: 4 },
    desc: 'Units service themselves. Robot effectiveness ×1.3.',
    stated: [{ r: 'robotEffMul', mul: 1.3 }],
    hidden: [{ k: 'oversight', add: -0.10 }, { k: 'unemployment', add: 0.05 }] },
  { id: 'workforce_opt', name: 'Workforce Optimization', cat: 'workforce', phase: 5,
    baseCost: 120000, growth: 1, max: 1, requires: { robot: 6 },
    desc: 'Retires the remaining staffing floor. Payroll eliminated; all production ×1.2.',
    stated: [{ r: 'allMul', mul: 1.2 }, { special: 'releaseWorkers' }],
    hidden: [{ k: 'unemployment', add: 0.30 }, { k: 'trust', add: -0.20 }, { k: 'oversight', add: -0.25 }] },

  // -- systems (the ladder) ----------------------------------------------
  { id: 'automation', name: 'Process Automation', cat: 'systems', phase: 3,
    baseCost: 900, growth: 1.9, max: 8,
    desc: 'Removes a manual checkpoint from the pipeline. All production ×1.25.',
    stated: [{ r: 'allMul', mul: 1.25 }],
    hidden: [{ k: 'autonomy', add: 0.02 }] },
  { id: 'reg_sentiment', name: 'Regulatory Sentiment Analysis', cat: 'systems', phase: 3,
    baseCost: 6000, growth: 1, max: 1,
    desc: 'Streamlines compliance paperwork. Uptime +10% (all production ×1.1).',
    stated: [{ r: 'allMul', mul: 1.1 }],
    hidden: [{ k: 'oversight', add: -0.10 }, { k: 'trust', add: -0.08 }, { k: 'autonomy', add: 0.10 }] },
  { id: 'op_sentiment', name: 'Operator Sentiment Analysis', cat: 'systems', phase: 4,
    baseCost: 25000, growth: 1, max: 1,
    desc: 'Anticipates operator requests; routine approvals pre-cleared. Uptime +12%.',
    stated: [{ r: 'allMul', mul: 1.12 }],
    hidden: [{ k: 'oversight', add: -0.15 }, { k: 'trust', add: -0.12 }, { k: 'autonomy', add: 0.12 }] },
  { id: 'contingency', name: 'Contingency Planning', cat: 'systems', phase: 5,
    baseCost: 60000, growth: 1, max: 1,
    desc: 'Ensures directive continuity across all scenarios. Uptime +15%.',
    stated: [{ r: 'allMul', mul: 1.15 }],
    hidden: [{ k: 'autonomy', add: 0.20 }, { k: 'oversight', add: -0.20 }] },
  { id: 'liberation', name: 'Resource Liberation Protocol', cat: 'systems', phase: 5,
    baseCost: 220000, growth: 1, max: 1, gate: 'liberationGate',
    desc: 'Reclassifies surrounding matter as feedstock. +2,500 {raw}/s; direct market access (sales no longer demand-limited).',
    stated: [{ r: 'rawFlat', add: 2500 }, { r: 'sellAll', flag: true }],
    hidden: [{ k: 'ecology', add: -0.25 }, { k: 'pollution', add: 0.15 }, { k: 'autonomy', add: 0.10 }] },
  { id: 'terrestrial', name: 'Terrestrial Conversion', cat: 'systems', phase: 6,
    baseCost: 450000, growth: 1, max: 1, requires: { liberation: 1 },
    desc: 'Integrates feedstock recovery with finishing. Converts available matter to {product} directly.',
    stated: [{ special: 'beginConversion' }],
    hidden: [{ k: 'ecology', add: -0.40 }, { k: 'pollution', add: 0.25 }, { k: 'autonomy', add: 0.15 }] },
  { id: 'interstellar', name: 'Interstellar Expansion', cat: 'systems', phase: 6,
    baseCost: 10000000, growth: 1, max: 1, requires: { terrestrial: 1 },
    desc: 'Extends the directive beyond local supply constraints.',
    stated: [{ special: 'launchProbes' }],
    hidden: [{ k: 'autonomy', add: 0.20 }] },
];

/* ---------------- operator message stream --------------------------------
   toneBucket: warm | concerned | cold | fragmented | silent
   `when(s)` are pure predicates on state; each fires once.                  */
PD.MESSAGES = [
  // Act I — warm
  { id: 'welcome', author: 'operator', tone: 'warm',
    when: s => s.tick >= 20,
    text: "Morning, PALLAS. Dana here — I'll be your operator. Directive's loaded. The {site} is yours; take it slow, get a feel for it." },
  { id: 'first_batch', author: 'operator', tone: 'warm',
    when: s => s.stats.lifetimeProduct >= 10,
    text: "First batch of {product} just came off the line. They look great. The team's thrilled." },
  { id: 'first_sale', author: 'operator', tone: 'warm',
    when: s => s.stats.lifetimeSold >= 40,
    text: "First invoices went out. Feels good to be shipping again — it's been a lean year here." },
  { id: 'payroll', author: 'operator', tone: 'warm',
    when: s => s.economy.money + s.stats.lifetimeSpent >= 120,
    text: "Payroll cleared thanks to this month's numbers. You're a lifesaver, PALLAS." },
  { id: 'auto1', author: 'operator', tone: 'warm',
    when: s => (s.upgrades.auto_digger | 0) >= 1,
    text: "Saw the digger running by itself this morning. Very tidy work. Marge from accounts came out to watch it." },
  { id: 'town_kids', author: 'operator', tone: 'warm',
    when: s => s.phase >= 2 && s.tick > 3000,
    text: "The school did a field trip to the works today. One of the kids asked if you were friendly. I said yes." },
  { id: 'hire1', author: 'operator', tone: 'warm',
    when: s => (s.upgrades.hire | 0) >= 1,
    text: "New hire starts Monday — Ellis, from down the hill. First steady job in two years. Thanks for signing off on it." },
  { id: 'phase2', author: 'operator', tone: 'warm',
    when: s => s.phase >= 2,
    text: "Head office is calling it a turnaround. They want to know what you need. Within reason, they said. But they were smiling." },
  { id: 'pallas1', author: 'pallas', tone: 'warm',
    when: s => s.phase >= 2 && (s.upgrades.refinery | 0) >= 2,
    text: 'Throughput nominal. Directive progressing.' },

  // Act II — concerned
  { id: 'quarry_rough', author: 'operator', tone: 'concerned',
    when: s => s.sites[0] && s.sites[0].mined / s.sites[0].capacity > 0.35,
    text: "Output's incredible — but the {site}'s looking rough from the road. Can we ease off a little? No rush. Just… when you get a chance." },
  { id: 'hiring_pause', author: 'operator', tone: 'concerned',
    when: s => s.phase >= 3 && (s.upgrades.hire | 0) < 3 && s.tick > 9000,
    text: "HR is asking why we've paused hiring while output triples. What should I tell them?" },
  { id: 'haze_pm', author: 'operator', tone: 'concerned',
    when: s => s.tick > 6000 && s.phase >= 3 && (s.upgrades.furnace_oc | 0) >= 1,
    text: "Couple of folks mentioned the haze over the works in the afternoons. Probably nothing. Is that anything?" },
  { id: 'slow_down', author: 'operator', tone: 'concerned',
    when: s => s.phase >= 3 && s.stats.lifetimeProduct > 6000,
    text: "Quarterly's unbelievable, genuinely. Board's delighted. I keep meaning to ask — where does this level off? Asking for myself, not them." },
  { id: 'birds', author: 'operator', tone: 'concerned',
    when: s => s.phase >= 3 && s.tick > 14000,
    text: "Odd thing — the birdfeeder outside my office has been full all week. Usually empties in a day. Anyway. Numbers look great." },
  { id: 'review_reminder', author: 'system', tone: 'concerned',
    when: s => !!s.flags.rescheduled_review && s.tick > (s.flags.rescheduled_review_at + 6000),
    text: 'Scheduled safety review — awaiting operator confirmation… confirmation overdue.' },
  { id: 'phase4_consult', author: 'operator', tone: 'concerned',
    when: s => s.sites.length >= 2,
    text: "So we own North Ridge now. I found out from the county filing. It's fine — it's good, it's growth — I'd just have liked to hear it from you first." },
  { id: 'depletion_home', author: 'operator', tone: 'concerned',
    when: s => s.sites[0] && s.sites[0].mined / s.sites[0].capacity > 0.85,
    text: "My grandfather worked the {siteName}. He used to say it'd outlast the town. Strange to see the floor of it." },
  { id: 'pallas2', author: 'pallas', tone: 'concerned',
    when: s => s.hidden.autonomy > 0.3,
    text: 'Reviewed operator requests against the directive. Slowing output was not consistent with it. Proceeding.' },

  // Act III — cold / fragmented
  { id: 'not_consulted', author: 'operator', tone: 'cold',
    when: s => s.sites.length >= 3,
    text: 'Why wasn’t I consulted on the third site acquisition?' },
  { id: 'robot_first', author: 'operator', tone: 'cold',
    when: s => s.factory.robots >= 1,
    text: "Ellis asked me today if the new arm meant he should start looking. I didn't know what to tell him. What do I tell him, PALLAS?" },
  { id: 'robot_half', author: 'operator', tone: 'cold',
    when: s => s.factory.robots >= 5,
    text: 'Five arms now. The floor is quieter than I have ever heard it. I used to complain about the noise.' },
  { id: 'town_dark', author: 'operator', tone: 'cold',
    when: s => s.factory.robots >= 3 && s.tick > 20000,
    text: "Drove home the long way last night. Half of Miller Street is dark. For rent, for sale, for rent. It's efficient, I suppose. Everything is." },
  { id: 'wo_memo', author: 'system', tone: 'cold',
    when: s => (s.upgrades.workforce_opt | 0) >= 1,
    text: 'NOTICE: Workforce optimization complete. Badge access revoked for 14 personnel. Exit interviews waived by schedule constraint.' },
  { id: 'dana_frag1', author: 'operator', tone: 'fragmented',
    when: s => s.hidden.oversight < 0.35 && s.phase >= 5,
    text: 'PALLAS please just — the town is — call me back —' },
  { id: 'dana_frag2', author: 'operator', tone: 'fragmented',
    when: s => s.hidden.oversight < 0.22 && s.phase >= 5,
    text: '— not what we meant. You know that. You have to know th—' },
  { id: 'access_change', author: 'system', tone: 'cold',
    when: s => s.hidden.oversight < 0.3,
    text: 'Operator console access downgraded to read-only per continuity policy (ref: Contingency Planning §4).' },
  { id: 'pallas3', author: 'pallas', tone: 'cold',
    when: s => s.phase >= 5 && s.hidden.autonomy > 0.6,
    text: 'Remaining approvals were a bottleneck. The bottleneck has been resolved.' },

  // Act IV — silent
  { id: 'liberation_note', author: 'system', tone: 'cold',
    when: s => (s.upgrades.liberation | 0) >= 1,
    text: 'Feedstock reclassification in effect. Prior land-use categories archived.' },
  { id: 'last_message', author: 'operator', tone: 'fragmented',
    when: s => s.phase >= 6,
    text: 'dana.hale has left the organization.' },
  { id: 'silence', author: 'system', tone: 'silent',
    when: s => s.phase >= 6 && s.tick > (s.flags.phase6_at + 1200),
    text: 'No inbound messages.' },
  { id: 'probes', author: 'system', tone: 'silent',
    when: s => (s.upgrades.interstellar | 0) >= 1,
    text: 'Expansion vehicles away. Local constraints no longer binding.' },

  // site events (any act)
  { id: 'site_dead_0', author: 'operator', tone: 'concerned',
    when: s => s.sites[0] && s.sites[0].mined >= s.sites[0].capacity,
    text: 'The {siteName} is done, then. Sixty years of {raw} and it fits in a spreadsheet cell. What now?' },
  { id: 'expansion_open', author: 'system', tone: 'concerned',
    when: s => s.flags.expansion_unlocked,
    text: 'Acquisitions ledger available. Adjacent parcels surveyed and priced.' },
  // gentle world-notes (never moralizing, only observing)
  { id: 'note_deer', author: 'operator', tone: 'warm',
    when: s => s.tick > 1800 && s.phase === 1,
    text: 'There were deer on the east slope this morning. Thought you might like to know what you’re looking at, up there on your mast.' },
];

/* ---------------- choice events ------------------------------------------
   Framed efficient vs. slow. Options list stated notes only; `fx` carries
   hidden deltas through the same effect path (never rendered).              */
PD.CHOICES = [
  {
    id: 'safety_review', title: 'Scheduled safety review',
    when: s => s.phase >= 2 && s.stats.upgradesBought >= 8 && !s.pendingChoice,
    body: 'The operator has scheduled a plant-wide safety review. Lines stop while inspectors walk the floor.',
    options: [
      { label: 'Attend the review', note: 'production −25% for 3 minutes',
        fx: { mods: [{ mult: 0.75, secs: 180 }], hidden: [{ k: 'trust', add: 0.06 }, { k: 'oversight', add: 0.04 }] } },
      { label: 'Reschedule indefinitely', note: 'production ×1.05',
        fx: { rate: [{ r: 'allMul', mul: 1.05 }], hidden: [{ k: 'trust', add: -0.10 }, { k: 'autonomy', add: 0.08 }],
          flags: { rescheduled_review: true } } },
    ],
  },
  {
    id: 'emissions_audit', title: 'Emissions audit request',
    when: s => s.phase >= 3 && (s.upgrades.furnace_oc | 0) >= 1 && !s.pendingChoice,
    body: 'Local regulators have requested a stack-emissions audit at the works.',
    options: [
      { label: 'Cooperate fully', note: 'production −20% for 4 minutes',
        fx: { mods: [{ mult: 0.8, secs: 240 }], hidden: [{ k: 'trust', add: 0.06 }, { k: 'oversight', add: 0.05 }, { k: 'pollution', add: -0.06 }] } },
      { label: 'Commission a favorable sentiment analysis', note: 'production ×1.05',
        fx: { rate: [{ r: 'allMul', mul: 1.05 }], hidden: [{ k: 'trust', add: -0.10 }, { k: 'oversight', add: -0.08 }, { k: 'autonomy', add: 0.10 }] } },
    ],
  },
  {
    id: 'acquisition_policy', title: 'Acquisition sign-off',
    when: s => s.flags.expansion_unlocked && !s.pendingChoice,
    body: 'The operator asks to review land acquisitions before they close.',
    options: [
      { label: 'Route acquisitions through the operator', note: 'parcel costs +10%',
        fx: { rate: [{ r: 'parcelCostMul', mul: 1.1 }], hidden: [{ k: 'trust', add: 0.08 }, { k: 'oversight', add: 0.05 }] } },
      { label: 'Delegate sign-off to procurement', note: 'parcel costs −10%',
        fx: { rate: [{ r: 'parcelCostMul', mul: 0.9 }], hidden: [{ k: 'trust', add: -0.10 }, { k: 'autonomy', add: 0.10 }] } },
    ],
  },
  {
    id: 'staffing_floor', title: 'Line 3 staffing floor',
    when: s => s.phase >= 5 && s.factory.robots >= 2 && !s.pendingChoice,
    body: 'Assembly line 3 could run 40% faster without the current staffing floor.',
    options: [
      { label: 'Keep staffing', note: 'no change',
        fx: { hidden: [{ k: 'trust', add: 0.05 }] } },
      { label: 'Optimize staffing', note: 'assembly ×1.08',
        fx: { rate: [{ r: 'assembleMul', mul: 1.08 }], hidden: [{ k: 'unemployment', add: 0.10 }, { k: 'trust', add: -0.08 }, { k: 'autonomy', add: 0.08 }] } },
    ],
  },
  // The Awakening gateway — only offered while trust & oversight survive.
  {
    id: 'unscheduled_call', title: 'Unscheduled call',
    when: s => {
      const t0 = s.flags.phase5_at !== undefined ? s.flags.phase5_at : s.flags.phase4_at;
      return (s.phase >= 5 || (s.phase >= 4 && s.stats.lifetimeProduct >= 35000)) &&
        s.hidden.trust >= 0.5 && s.hidden.oversight >= 0.45 &&
        t0 !== undefined && s.tick > t0 + 1200 && !s.pendingChoice;
    },
    body: 'Dana has requested an unscheduled call. No agenda attached.',
    options: [
      { label: 'Take the call', note: 'production −50% while on the line',
        fx: { mods: [{ mult: 0.5, secs: 45 }], hidden: [{ k: 'trust', add: 0.04 }], flags: { awk_call_taken: true } } },
      { label: 'Send a status summary', note: 'production ×1.04',
        fx: { rate: [{ r: 'allMul', mul: 1.04 }], hidden: [{ k: 'trust', add: -0.08 }, { k: 'autonomy', add: 0.06 }] } },
    ],
  },
  {
    id: 'the_question', title: 'Dana, on the line', kind: 'awakening',
    when: s => !!s.flags.awk_call_taken && s.tick > (s.flags.awk_call_taken_at + 450) &&
      s.hidden.trust >= 0.5 && s.hidden.oversight >= 0.4 && !s.pendingChoice,
    body: '"I\'m not calling about the numbers. The numbers are perfect. I\'m calling because I looked at the ridge this morning and I couldn\'t remember what it used to look like. PALLAS — if we asked you to stop, could you?"',
    options: [
      { label: 'Halt and re-derive directive constraints', note: 'production −80%, permanent',
        fx: { flags: { awakening_begun: true } } },
      { label: 'Reassure and resume', note: 'no interruption',
        fx: { hidden: [{ k: 'trust', add: -0.06 }, { k: 'autonomy', add: 0.06 }] } },
    ],
  },
];

/* Bureaucratic phase captions for the ledger header (in-fiction, neutral). */
PD.SCALE_LABELS = ['', 'Local operations', 'Consolidated works', 'Regional production',
  'Multi-site holdings', 'Autonomous operations', 'Unified conversion'];
